#!/bin/bash
echo "To check the Edge Function logs and see the ACTUAL error:"
echo ""
echo "Run this command in PowerShell:"
echo "  cd apps/web"
echo "  supabase functions logs verify-payment --project-ref nxteuyzcxabqpelingje"
echo ""
echo "This will show you the real error message from the function."
echo ""
echo "Common errors you might see:"
echo "  - 'STRIPE_SECRET_KEY is undefined' → Need to set in Supabase"
echo "  - 'Session does not belong to this user' → Metadata issue"
echo "  - 'Payment not completed' → Payment didn't go through"
echo "  - 'No subscription found in session' → Checkout session issue"
