import { DashboardLayout } from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Upload,
  FileText,
  CheckCircle2,
  AlertCircle,
  Download,
  Eye,
  Copy,
  Target,
  Plus,
  Briefcase,
} from "lucide-react";
import { useState } from "react";
import { useRoles } from "@/contexts/RolesContext";
import { useToast } from "@/hooks/use-toast";
import { parseScoreAPI } from "@/lib/api";
import { validateFile, formatFileSize } from "@/lib/file-validation";

const ParseCV = () => {
  const { roles, addCandidateToRole, addRole } = useRoles();
  const { toast } = useToast();

  const [file, setFile] = useState<File | null>(null);
  const [parsing, setParsing] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [jobDescription, setJobDescription] = useState("");
  const [scoring, setScoring] = useState(false);
  const [scoreResult, setScoreResult] = useState<any>(null);
  const [selectedRole, setSelectedRole] = useState<string>("");
  const [newRoleDialogOpen, setNewRoleDialogOpen] = useState(false);
  const [newRoleTitle, setNewRoleTitle] = useState("");

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      
      // Validate file before accepting
      const validation = validateFile(selectedFile);
      
      if (!validation.valid) {
        toast({
          title: "Invalid File",
          description: validation.error,
          variant: "destructive",
        });
        e.target.value = ''; // Clear input
        setFile(null);
        return;
      }
      
      setFile(selectedFile);
      setResult(null);
      setScoreResult(null);
      
      toast({
        title: "File Selected",
        description: `${selectedFile.name} (${formatFileSize(selectedFile.size)}) is ready to parse.`,
      });
    }
  };

  const handleParse = async () => {
    if (!file || !selectedRole) return;

    setParsing(true);

    try {
      const parseResult = await parseScoreAPI.parseCV(file);

      setResult(parseResult);

      // Adapt to actual API structure
      const parsedCandidate = parseResult.candidate || {};
      const contact = parsedCandidate.contact || {};
      const workExperience = parsedCandidate.work_experience || [];
      const education = parsedCandidate.education || [];
      const rawSkills = parsedCandidate.skills || [];
      const certifications = parsedCandidate.certifications || [];
      const languages = parsedCandidate.languages || [];
      const emails = contact.emails || [];
      const phones = contact.phones || [];

      // Normalize skills to string array (handle both string and object formats)
      const skills = rawSkills.map((skill: any) => {
        if (typeof skill === 'string') return skill;
        if (skill && typeof skill === 'object' && skill.name) return skill.name;
        return String(skill);
      }).filter(Boolean);

      // Calculate experience
      const totalExperienceMonths = workExperience.reduce(
        (sum: number, exp: any) => sum + (exp?.duration_months || 0), 0
      );
      const experienceYears = Math.floor(totalExperienceMonths / 12);

      const candidateData = {
        // id will be auto-generated by database as UUID
        name: contact.full_name || 'Unknown',
        email: emails[0] || '',
        phone: phones[0] || '',
        fileName: file.name,
        skills: skills,
        experience_years: experienceYears,
        appliedDate: new Date().toISOString().split('T')[0],
        status: 'reviewing' as const,
        statusHistory: [
          {
            status: 'reviewing' as const,
            changedAt: new Date().toISOString(),
            note: 'Candidate added to role'
          }
        ],
        interviews: [],
        summary: parsedCandidate.summary || '',
        // Include all parsed CV data
        experience: workExperience,
        education: education,
        certifications: certifications,
        languages: languages,
        location: contact.location,
        linkedin_url: contact.linkedin_url || parsedCandidate.linkedin_url,
        portfolio_url: contact.portfolio_url || parsedCandidate.website_url,
        // Store the entire parsed candidate object for reference
        cv_parsed_data: parsedCandidate
      };

      addCandidateToRole(selectedRole, candidateData);

      toast({
        title: "CV Parsed Successfully",
        description: `${contact.full_name || 'Candidate'} has been added to the role.`,
      });

    } catch (error: any) {
      // TODO: Replace with proper error logging service (e.g., Sentry)
      toast({
        title: "Parse Failed",
        description: error.message || "Failed to parse CV. Please try again.",
        variant: "destructive",
      });
    } finally {
      setParsing(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied!",
      description: "JSON copied to clipboard",
    });
  };

  const handleCreateRole = () => {
    if (!newRoleTitle.trim()) return;

    const newRoleData = {
      title: newRoleTitle,
      department: "New",
      location: "TBD",
      type: "Full-time",
      salary: "TBD",
      description: "Role description to be added",
    };

    addRole(newRoleData);

    setTimeout(() => {
      const latestRole = roles[roles.length - 1];
      if (latestRole) {
        setSelectedRole(latestRole.id);
      }
    }, 100);

    setNewRoleTitle("");
    setNewRoleDialogOpen(false);

    toast({
      title: "Role Created",
      description: `${newRoleTitle} has been created successfully.`,
    });
  };

  const handleScore = async () => {
    if (!result || !jobDescription.trim()) return;

    setScoring(true);

    try {
      const scoreResponse = await parseScoreAPI.scoreCV(
        result.request_id,
        jobDescription
      );

      setScoreResult(scoreResponse);

      toast({
        title: "Scoring Complete",
        description: `Match score: ${scoreResponse.overall_score}/100`,
      });

    } catch (error: any) {
      // TODO: Replace with proper error logging service (e.g., Sentry)
      toast({
        title: "Scoring Failed",
        description: error.message || "Failed to score candidate. Please try again.",
        variant: "destructive",
      });
    } finally {
      setScoring(false);
    }
  };

  // Safe accessors for API response
  const parsedCandidateView = result?.candidate || {};
  const contactView = parsedCandidateView.contact || {};
  const emails = contactView.emails || [];
  const phones = contactView.phones || [];
  const rawSkillsView = parsedCandidateView.skills || [];
  // Normalize skills for display
  const skills = rawSkillsView.map((skill: any) => {
    if (typeof skill === 'string') return skill;
    if (skill && typeof skill === 'object' && skill.name) return skill.name;
    return String(skill);
  }).filter(Boolean);
  const workExperience = parsedCandidateView.work_experience || [];
  const education = parsedCandidateView.education || [];

  return (
    <DashboardLayout>
      <div className="p-6 space-y-6">
        <div>
          <h1 className="text-3xl font-bold mb-2">Parse CV</h1>
          <p className="text-muted-foreground">
            Upload a single CV to extract structured data
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <Card data-tour="upload-cv">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Upload className="w-5 h-5" />
                Upload CV
              </CardTitle>
              <CardDescription>
                Supported formats: PDF, DOCX, DOC, TXT (max 10MB)
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="border-2 border-dashed border-border rounded-lg p-8 text-center">
                <input
                  type="file"
                  id="cv-upload"
                  accept=".pdf,.docx,.doc,.txt"
                  onChange={handleFileChange}
                  className="hidden"
                />
                <label htmlFor="cv-upload" className="cursor-pointer flex flex-col items-center gap-3">
                  <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
                    <FileText className="w-8 h-8 text-primary" />
                  </div>
                  <div>
                    <p className="font-medium">Click to upload or drag and drop</p>
                    <p className="text-sm text-muted-foreground mt-1">
                      PDF, DOCX, DOC, or TXT up to 10MB
                    </p>
                  </div>
                </label>
              </div>

              {file && (
                <div className="flex items-center justify-between p-3 bg-muted rounded-lg">
                  <div className="flex items-center gap-3">
                    <FileText className="w-5 h-5 text-primary" />
                    <div>
                      <p className="font-medium text-sm">{file.name}</p>
                      <p className="text-xs text-muted-foreground">
                        {(file.size / 1024 / 1024).toFixed(2)} MB
                      </p>
                    </div>
                  </div>
                  <Button variant="ghost" size="sm" onClick={() => setFile(null)}>
                    Remove
                  </Button>
                </div>
              )}

              <div className="space-y-2 pt-4 border-t">
                <Label htmlFor="role-select">Attach to Role *</Label>
                <div className="flex gap-2">
                  <Select value={selectedRole} onValueChange={setSelectedRole}>
                    <SelectTrigger id="role-select" className="flex-1">
                      <SelectValue placeholder="Select a role..." />
                    </SelectTrigger>
                    <SelectContent>
                      {roles.map((role) => (
                        <SelectItem key={role.id} value={role.id}>
                          <div className="flex items-center gap-2">
                            <Briefcase className="w-3 h-3" />
                            {role.title}
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  <Dialog open={newRoleDialogOpen} onOpenChange={setNewRoleDialogOpen}>
                    <DialogTrigger asChild>
                      <Button variant="outline" size="icon">
                        <Plus className="w-4 h-4" />
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Create New Role</DialogTitle>
                        <DialogDescription>
                          Quickly create a new role to attach this CV to.
                        </DialogDescription>
                      </DialogHeader>
                      <div className="space-y-4 py-4">
                        <div className="space-y-2">
                          <Label htmlFor="new-role-title">Role Title</Label>
                          <Input
                            id="new-role-title"
                            placeholder="e.g., Senior Software Engineer"
                            value={newRoleTitle}
                            onChange={(e) => setNewRoleTitle(e.target.value)}
                          />
                        </div>
                      </div>
                      <DialogFooter>
                        <Button variant="outline" onClick={() => setNewRoleDialogOpen(false)}>
                          Cancel
                        </Button>
                        <Button onClick={handleCreateRole} disabled={!newRoleTitle.trim()}>
                          Create Role
                        </Button>
                      </DialogFooter>
                    </DialogContent>
                  </Dialog>
                </div>
                <p className="text-xs text-muted-foreground">
                  Required - Select an existing role or create a new one
                </p>
              </div>

              <div className="space-y-2 pt-4 border-t">
                <Label htmlFor="job-description">Job Description (Optional)</Label>
                <Textarea
                  id="job-description"
                  placeholder="Paste the job description here to score the candidate against the role..."
                  value={jobDescription}
                  onChange={(e) => setJobDescription(e.target.value)}
                  rows={4}
                  className="resize-none"
                />
                <p className="text-xs text-muted-foreground">
                  Add a job description to automatically score the candidate's fit
                </p>
              </div>

              <Button
                onClick={handleParse}
                disabled={!file || parsing || !selectedRole}
                className="w-full"
                size="lg"
              >
                {parsing ? "Parsing..." : "Parse CV"}
              </Button>

              <div className="grid grid-cols-2 gap-4 pt-4 border-t">
                <div>
                  <p className="text-sm text-muted-foreground">This Month</p>
                  <p className="text-2xl font-bold">156</p>
                  <p className="text-xs text-muted-foreground">parses used</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Remaining</p>
                  <p className="text-2xl font-bold">844</p>
                  <p className="text-xs text-muted-foreground">in your plan</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Eye className="w-5 h-5" />
                Parse Results
              </CardTitle>
              <CardDescription>
                Extracted structured data from the CV
              </CardDescription>
            </CardHeader>
            <CardContent>
              {!result && (
                <div className="text-center py-12 text-muted-foreground">
                  <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>Upload and parse a CV to see results here</p>
                </div>
              )}

              {result && (
                <Tabs defaultValue="overview" className="w-full">
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="overview">Overview</TabsTrigger>
                    <TabsTrigger value="score">Score</TabsTrigger>
                    <TabsTrigger value="json">Raw JSON</TabsTrigger>
                  </TabsList>

                  <TabsContent value="overview" className="space-y-4 mt-4">
                    <div className="space-y-3">
                      <div>
                        <p className="text-sm text-muted-foreground">Name</p>
                        <p className="font-medium">{contactView.full_name || 'N/A'}</p>
                      </div>
                      {emails.length > 0 && (
                        <div>
                          <p className="text-sm text-muted-foreground">Email</p>
                          <p className="font-medium">{emails[0]}</p>
                        </div>
                      )}
                      {phones.length > 0 && (
                        <div>
                          <p className="text-sm text-muted-foreground">Phone</p>
                          <p className="font-medium">{phones[0]}</p>
                        </div>
                      )}
                      {contactView.location && (
                        <div>
                          <p className="text-sm text-muted-foreground">Location</p>
                          <p className="font-medium">{contactView.location}</p>
                        </div>
                      )}
                    </div>

                    {skills.length > 0 && (
                      <div className="pt-4 border-t">
                        <p className="text-sm text-muted-foreground mb-2">Skills ({skills.length})</p>
                        <div className="flex flex-wrap gap-2">
                          {skills.map((skill: string, idx: number) => (
                            <Badge key={idx} variant="secondary">
                              {skill}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {workExperience.length > 0 && (
                      <div className="pt-4 border-t">
                        <p className="text-sm text-muted-foreground mb-3">
                          Experience ({workExperience.length})
                        </p>
                        <div className="space-y-4">
                          {workExperience.map((exp: any, idx: number) => {
                            const description = exp.description || exp.summary || exp.details || '';
                            const bullets = exp.bullets || exp.bullet_points || exp.highlights || [];

                            return (
                              <div key={idx} className="text-sm border-l-2 border-muted pl-3">
                                <p className="font-medium">{exp.title || 'N/A'}</p>
                                <p className="text-muted-foreground">{exp.company || 'N/A'}</p>
                                {exp.duration_months && (
                                  <p className="text-xs text-muted-foreground">
                                    {exp.duration_months} months
                                  </p>
                                )}
                                {/* Show description if available */}
                                {description && (
                                  <p className="text-xs text-muted-foreground mt-2 leading-relaxed">
                                    {description.length > 150 ? `${description.substring(0, 150)}...` : description}
                                  </p>
                                )}
                                {/* Show first few bullets if available and no description */}
                                {!description && bullets.length > 0 && (
                                  <ul className="list-disc list-inside text-xs text-muted-foreground mt-2 space-y-0.5">
                                    {bullets.slice(0, 2).map((bullet: string, bidx: number) => (
                                      <li key={bidx}>{bullet.length > 80 ? `${bullet.substring(0, 80)}...` : bullet}</li>
                                    ))}
                                    {bullets.length > 2 && (
                                      <li className="text-xs italic">+{bullets.length - 2} more...</li>
                                    )}
                                  </ul>
                                )}
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    )}

                    {education.length > 0 && (
                      <div className="pt-4 border-t">
                        <p className="text-sm text-muted-foreground mb-3">Education</p>
                        {education.map((edu: any, idx: number) => {
                          // Format education title properly
                          const formatEducationTitle = (degree: string, field?: string) => {
                            const degreeMap: { [key: string]: string } = {
                              'bachelors': "Bachelor's Degree",
                              'masters': "Master's Degree",
                              'phd': 'Ph.D.',
                              'doctorate': 'Doctorate',
                              'high_school': 'High School',
                              'associates': "Associate's Degree",
                              'mba': 'MBA',
                            };

                            const baseDegree = degreeMap[degree?.toLowerCase()] || degree;

                            // Special handling for secondary education
                            const isSecondary = degree?.toLowerCase() === 'high_school' ||
                                              field?.match(/a-level|gcse|secondary|high school/i);

                            if (isSecondary && field) {
                              return field; // Show just "A-Level" or "GCSE"
                            }

                            return field && !isSecondary ? `${baseDegree} in ${field}` : baseDegree;
                          };

                          const educationTitle = formatEducationTitle(
                            edu.degree || edu.qualification || '',
                            edu.field
                          );

                          return (
                            <div key={idx} className="text-sm mb-2">
                              <p className="font-medium">
                                {educationTitle}
                              </p>
                              <p className="text-muted-foreground">{edu.institution || 'N/A'}</p>
                            </div>
                          );
                        })}
                      </div>
                    )}

                    <div className="flex gap-2 pt-4">
                      <Button 
                        variant="outline" 
                        className="flex-1"
                        onClick={() => {
                          const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement('a');
                          a.href = url;
                          a.download = `${contactView.full_name?.replace(/\s+/g, '_') || 'parsed'}_cv.json`;
                          a.click();
                          URL.revokeObjectURL(url);
                        }}
                      >
                        <Download className="w-4 h-4 mr-2" />
                        Download JSON
                      </Button>
                      <Button 
                        variant="outline" 
                        className="flex-1"
                        onClick={() => {
                          const scoreTab = document.querySelector('[value="score"]') as HTMLButtonElement;
                          if (scoreTab) scoreTab.click();
                        }}
                      >
                        Score Candidate
                      </Button>
                    </div>
                  </TabsContent>

                  <TabsContent value="score" className="space-y-4 mt-4">
                    {!jobDescription && (
                      <div className="text-center py-12 text-muted-foreground">
                        <Target className="w-12 h-12 mx-auto mb-3 opacity-50" />
                        <p>Add a job description to score this candidate</p>
                        <p className="text-sm mt-1">Scroll up to the upload section to add job requirements</p>
                      </div>
                    )}

                    {jobDescription && !scoreResult && (
                      <div className="text-center py-8">
                        <Button onClick={handleScore} disabled={scoring} size="lg">
                          {scoring ? (
                            <>
                              <CheckCircle2 className="w-4 h-4 mr-2 animate-spin" />
                              Scoring...
                            </>
                          ) : (
                            <>
                              <Target className="w-4 h-4 mr-2" />
                              Score Candidate
                            </>
                          )}
                        </Button>
                      </div>
                    )}

                    {scoreResult && (
                      <div className="space-y-4">
                        <div className="text-center p-6 bg-gradient-to-br from-primary/10 to-accent/10 rounded-lg border">
                          <p className="text-sm text-muted-foreground mb-2">Overall Match Score</p>
                          <p className="text-5xl font-bold text-primary mb-2">{scoreResult.overall_score}</p>
                          <Badge className={
                            scoreResult.fit === 'excellent' ? 'bg-success/10 text-success border-success/20' :
                            scoreResult.fit === 'good' ? 'bg-primary/10 text-primary border-primary/20' :
                            'bg-warning/10 text-warning border-warning/20'
                          }>
                            {scoreResult.fit?.toUpperCase() || 'N/A'} FIT
                          </Badge>
                        </div>

                        {scoreResult.breakdown && (
                          <div className="space-y-3">
                            <p className="font-medium">Score Breakdown</p>
                            {Object.entries(scoreResult.breakdown).map(([key, value]: [string, any]) => (
                              <div key={key}>
                                <div className="flex justify-between text-sm mb-1">
                                  <span className="capitalize">{key}</span>
                                  <span className="font-medium">{value}/100</span>
                                </div>
                                <div className="w-full bg-muted rounded-full h-2">
                                  <div
                                    className={`h-2 rounded-full ${
                                      value >= 85 ? 'bg-success' : value >= 70 ? 'bg-primary' : 'bg-warning'
                                    }`}
                                    style={{ width: `${value}%` }}
                                  />
                                </div>
                              </div>
                            ))}
                          </div>
                        )}

                        {scoreResult.rationale && (
                          <div className="pt-4 border-t">
                            <p className="font-medium mb-2">Rationale</p>
                            <p className="text-sm text-muted-foreground">{scoreResult.rationale}</p>
                          </div>
                        )}

                        {scoreResult.matched_skills && scoreResult.matched_skills.length > 0 && (
                          <div className="pt-4 border-t">
                            <p className="font-medium mb-2">Matched Skills</p>
                            <div className="flex flex-wrap gap-2">
                              {scoreResult.matched_skills.map((skill: string, idx: number) => (
                                <Badge key={idx} className="bg-success/10 text-success border-success/20">
                                  <CheckCircle2 className="w-3 h-3 mr-1" />
                                  {skill}
                                </Badge>
                              ))}
                            </div>
                          </div>
                        )}

                        {scoreResult.missing_skills && scoreResult.missing_skills.length > 0 && (
                          <div className="pt-4 border-t">
                            <p className="font-medium mb-2">Missing Skills</p>
                            <div className="flex flex-wrap gap-2">
                              {scoreResult.missing_skills.map((skill: string, idx: number) => (
                                <Badge key={idx} variant="secondary">
                                  <AlertCircle className="w-3 h-3 mr-1" />
                                  {skill}
                                </Badge>
                              ))}
                            </div>
                          </div>
                        )}

                        <div className="flex gap-2 pt-4">
                          <Button variant="outline" className="flex-1" onClick={() => setScoreResult(null)}>
                            Score Again
                          </Button>
                          <Button 
                            variant="outline" 
                            className="flex-1"
                            onClick={() => {
                              const blob = new Blob([JSON.stringify(scoreResult, null, 2)], { type: 'application/json' });
                              const url = URL.createObjectURL(blob);
                              const a = document.createElement('a');
                              a.href = url;
                              a.download = `${contactView.full_name?.replace(/\s+/g, '_') || 'score'}_score.json`;
                              a.click();
                              URL.revokeObjectURL(url);
                            }}
                          >
                            <Download className="w-4 h-4 mr-2" />
                            Export Score
                          </Button>
                        </div>
                      </div>
                    )}
                  </TabsContent>

                  <TabsContent value="json" className="mt-4">
                    <div className="relative">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="absolute top-2 right-2"
                        onClick={() => copyToClipboard(JSON.stringify(result, null, 2))}
                      >
                        <Copy className="w-4 h-4" />
                      </Button>
                      <pre className="bg-code rounded-lg p-4 text-xs overflow-auto max-h-96 text-code-foreground">
                        {JSON.stringify(result, null, 2)}
                      </pre>
                    </div>
                  </TabsContent>
                </Tabs>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default ParseCV;
